### PR TITLE
Shim Removal

### PR DESCRIPTION
**Pull request by Rspoon3**
`Shims.swift` is no longer needed since `sleep(for:tolerance:)` is now a [native function](https://developer.apple.com/documentation/swift/clock/sleep(for:tolerance:)).

### CODE REVIEW

**Comment by mbrandonw** [comment]
Hi @Rspoon3, while it is true `sleep(for:)` has been officially released, this library still supports older versions of Swift where it is not supported. So if we are going to remove the shims then we should also update Package.swift to be Swift 5.7. Would you mind adding that to this PR?

**Comment by Rspoon3** [comment]
@mbrandonw Yeah not a problem! Should the availability checks also be removed now?

**Comment by mbrandonw** [comment]
Yeah definitely, any mention of `swift(>=5.7)` can be removed.

**Comment by Rspoon3** [comment]
@mbrandonw Okay that should be everything now. Let me know if you'd like any other changes.

**Comment by mbrandonw** [comment]
Hi @Rspoon3, I think the changes to `platforms` in the Package.swift is going a little too far. That makes it so that packages that target iOS <16 cannot depend on this package, which means TCA could not even depend on it.

Can you revert that change and bring back all of the availability checks?

**Comment by Rspoon3** [comment]
All set.

**Review by mbrandonw — APPROVED** [review]
Thanks @Rspoon3!

**Pull request merged**
