### PR TITLE
Remove AsyncAlgorithms

### PR DESCRIPTION
**Pull request by brzzdev**
throttle -> _throttle
Remove select

### CODE REVIEW

**Comment by brzzdev** [comment]
Hi @mbrandonw, no worries. Happy to try and help :)

It looks like AsyncAlgorithms is only used in ClocksTests, so unless someone explicitly pulls in that test target, it shouldn't affect their version.

Tested this in a new project, pulling in swift-clocks only pulls down swift-concurrency-extras and xctest-dynamic-overlay.

Screenshot 2023-12-06 at 21 01 40

Still happy to try removing AsyncAlgorithms if you still think it's best, but I'd say there's value in testing how the clocks interact with it.

**Comment by brzzdev** [comment]
Screenshot 2023-12-06 at 21 05 32

To further test this, the same test app is happy to pull down 1.0.0 of AsyncAlgorithms even though the current production version of swift-clocks is relying on specific commit of it for it's testTarget.

**Comment by stephencelis** [comment]
@brzzdev I think we'd still prefer to remove the dependency entirely at this point. It was mainly helpful when first developing the library to validate against other code written by Apple.

**Comment by brzzdev** [comment]
Fair enough. 

Besides deleting the AsyncAlgorithmsTests file, the only other test relying on it was `testRunMultipleUnitsOfWork` where I replaced `AsyncTimerSequence` with your `clock.timer`

**Pull request merged**
